### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by bonigarcia** [fhg-fokus-nubomedia/nubomedia-media-client#1]
Hello,

So far nubomedia-media-client is in SNAPSHOT version. This implies that the project has to be cloned and installed in the local Maven repository to be used. This is understandable in development but IMHO it is not convenient at all for production.

Please, release a version of nubomedia-media-client to the Maven central repository ASAP, since this dependency is required to be used in production environment for demonstrators.

Thank you. Kind regards,
Boni

**Comment by acheambe** [comment]
Version 1.0 of nubomedia-media-client has been release and uploaded on maven central repository http://search.maven.org/#search%7Cga%7C1%7Cde.fhg

let me know if there are any problems using the library
